DROP TABLE RESERVATION;
DROP TABLE ROOM;
DROP TABLE US_ER;


CREATE TABLE ROOM (
  Room_No NUMBER NOT NULL PRIMARY KEY,
  Cap NUMBER NOT NULL
);

CREATE TABLE US_ER (
  User_No NUMBER NOT NULL PRIMARY KEY,
  User_Name VARCHAR(16) NOT NULL,
  Phone VARCHAR(12) NOT NULL
);

CREATE TABLE RESERVATION (
  Room_No NUMBER NOT NULL,
  User_No NUMBER NOT NULL,
  Reser_Date DATE NOT NULL,
  Start_time NUMBER,
  End_time NUMBER,
  FOREIGN KEY (Room_No) REFERENCES ROOM(Room_No),
  FOREIGN KEY (User_No) REFERENCES US_ER(User_No),
  PRIMARY KEY (Room_No, Reser_Date)
);

