DROP TABLE RESERVATION;
DROP TABLE ROOM;
DROP TABLE US_ER;


CREATE TABLE ROOM (
  Room_No NUMBER NOT NULL PRIMARY KEY,
  Cap NUMBER NOT NULL
);
COMMENT ON COLUMN ROOM.Room_No IS '룸번호';
COMMENT ON COLUMN ROOM.Cap IS '인원수';

CREATE TABLE US_ER (
  User_No NUMBER NOT NULL PRIMARY KEY,
  User_Name VARCHAR(16) NOT NULL,
  Phone VARCHAR(12) NOT NULL
);

COMMENT ON COLUMN US_ER.User_No IS '사용자번호';
COMMENT ON COLUMN US_ER.User_Name IS '이름';
COMMENT ON COLUMN US_ER.Phone IS '휴대폰';

CREATE TABLE RESERVATION (
  Room_No NUMBER NOT NULL,
  User_No NUMBER NOT NULL,
  Reser_Date DATE NOT NULL,
  Start_time NUMBER,
  End_time NUMBER,
  FOREIGN KEY (Room_No) REFERENCES ROOM(Room_No),
  FOREIGN KEY (User_No) REFERENCES US_ER(User_No),
  PRIMARY KEY (Room_No, Reser_Date)
);

COMMENT ON COLUMN RESERVATION.Room_No IS '룸번호';
COMMENT ON COLUMN RESERVATION.User_No IS '예약자';
COMMENT ON COLUMN RESERVATION.Reser_Date IS '예약날짜';
COMMENT ON COLUMN RESERVATION.Start_time IS '시작시간';
COMMENT ON COLUMN RESERVATION.End_time IS '끝시간';
